config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "lists#index"
  resources :lists, only: [:create, :new, :index, :show] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :list, scope: :movie
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :picture
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true
  validates :title, :overview, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list_id)

  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list_id = @list.id

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end


  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
    end

  def new
    @list = List.new

  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render "lists/new"
    end
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  private

  def list_params
    params.require(:list).permit(:name)

  end

  # def available_movies
  #   @list = List.find(params[:id])
  #   movies_in_list = @list.movies
  #   available_movies = Movie.all

  #   #Deleting all the movies that are in the list from the list of movies
  #   movies_in_list.each do |movie|
  #     available_movies.delete(movie)
  #   end

  #   return available_movies

  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag 'https://res.cloudinary.com/dkxostt6i/image/upload/v1650730982/movie-icon.png' %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New List", new_list_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="hero-image">
  <div class="hero-text">
    <h1>This is <strong>your</strong> movie watchlist</h1>
    <p>by movies unlimited</p>
     </div>
</div>


<div class="container">
  <h2>My Lists</h2>
    <div class="parent">
        <% @lists.each do |list| %>
      <%= link_to  list_path(list) do %>
        <div class="movie-card">
          <div class="card-img"><%= cl_image_tag list.picture.key, crop: :fill %></div>
            <div class="card-body">
            <p><%= list.name %></p>
            </div>
        </div>
      <% end %>
    <% end %>
    </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="row justify-content-left">
    <div class="col-4 my-3">
      <h2>Add a Review</h2>
      <%= simple_form_for @list do |f| %>
        <%= f.input :name, placeholder: "Add your list name" %>
        <%= f.input :picture, as: :file %>
        <%= f.submit "Add", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<%= cl_image_tag @list.picture.key, height: 300, width: 400, crop: :fill %>
<br>
<% @list.bookmarks.each do |bookmark| %>
<h2><%= bookmark.movie.title %></h2>
<p><%= bookmark.comment %></p>
<br>
<p><%=link_to "Delete me?", bookmark_path(bookmark),  method: :delete, data: { confirm: "Are you sure?" } %></p>
<% end %>

<p><%= link_to "<< Back to the home page", lists_path%></p>


<div class="container">
  <div class="row justify-content-left">
    <div class="col-4 my-3">
      <h4>Add a Bookmark</h4>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment, placeholder: "Add your comment" %>
        <%= f.association :movie, collection: Movie.all %>
        <%= f.submit "Add", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>